version: '3.8'

services:
  server:
    build: ./server
    ports:
      - '5050:5050'
    environment:
      - PORT=5050
      - MONGO_URI=mongodb+srv://kobe871230:Kobe24241230@myappuser.8l9vbna.mongodb.net/?retryWrites=true&w=majority&appName=myappuser
      - JWT_SECRET=supersecretkey
    restart: unless-stopped
